name: gym_project
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  timelines: ^0.1.0
  motion_tab_bar: ^0.1.5
  flutter:
    sdk: flutter
  hexcolor: ^2.0.5
  google_fonts: ^3.0.1
  pie_chart: ^5.0.0
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  intl: ^0.17.0
  cached_network_image: ^3.1.0
  flutter_custom_clippers: ^2.0.0
  bubble_tab_indicator: ^0.1.6
  backdrop: ^0.6.2
  multi_select_flutter: ^4.0.0
  image_picker: ^0.8.4
  provider: ^6.0.0
  video_player: ^2.2.3
  path_provider: ^2.0.4
  xfile: ^1.1.0
  pretty_json: ^2.0.0
  toggle_switch: ^1.2.0
  shared_preferences: ^2.0.7
  dots_indicator: ^2.0.0
  ansicolor: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  conditional_builder: ^1.0.2
  page_transition: "^1.1.7+6"
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  flutter_screenutil: ^5.5.4
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5
  flutter_datetime_picker: ^1.5.1
  fl_chart: ^0.55.2
  http_parser: ^4.0.1

  dio: ^4.0.6
  animations: ^2.0.2
  curved_navigation_bar: ^1.0.3
  dropdown_search: ^3.0.1
  flutter_svg: ^1.1.0

  percent_indicator: ^4.2.2

flutter_icons:
   image_path: assets/images/branch.png
   android: true
   ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa-Regular.ttf
        - asset: assets/fonts/Changa-Bold.ttf
          weight: 700
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.otf
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
