import 'package:gym_project/models/event.dart';
import 'package:gym_project/viewmodels/announcement-view-model.dart';
import 'package:gym_project/viewmodels/private-session-view-model.dart';
import 'models/admin-models/branches/branch-model.dart';
import 'models/admin-models/equipments/equipment-model.dart';
import 'models/admin-models/membership/membership-model.dart';
import 'models/admin-models/nutritionist-Sessions/nutritionistSession-model.dart';
import 'models/answer.dart';
import 'models/classes.dart';
import 'models/question.dart';
import 'models/supplementary.dart';
import 'models/user/coach_model.dart';
import 'models/user/member_model.dart';
import 'models/user/nutritionist_model.dart';

Coach userCoach;
Member userMember;
List<Member> membersUsers = [];
List<Coach> coachesUsers = [];
List<Nutritionist> nutritionistsUsers = [];
List<Branch> branchesList = [];
List<AnnouncementViewModel> announcementsList =[];
List<Equipment>allEquipment=[];
List<Classes> allClasses = [];
List<NutritionistSession> nutritionistSessions=[];
List<Membership> allMemberships =[];
List<PrivateSessionViewModel> privateSessions = [];
List<Question> questionsList = <Question>[];
List<Supplementary> supplementariesList = [];
List<Answer> answersList = [];
List<Event> allEvents = [];